//	Valid events generated by this interactive
//	Where message values are required to be objects, an array of any required properties is shown
//	Where message values are required to be some other data type, the required data type is shown as a string


rethink.events = {

	//	Session events (generic classes)
	'SessionStart': 										'sessionID',
	'SessionTimeoutStart': 							'sessionID',
	'SessionTimeoutCancel': 						'sessionID',
	'SessionTimeoutComplete': 					'sessionID',

	//	Mediaplayer events
	'VideoPlayThumbnail': 							'string',
	'VideoPlayAttract': 								'string',
	'VideoPlayAuto': 										'string',
	'VideoPlaybackComplete': 						'string',
	'VideoPause': 											'string',
	'VideoUnpause': 										'string',
	'VideoRewindDuringPlayback': 				'string',
	'VideoRewindPostPlayback': 					'string',
	'VideoBSLToggleOn': 								'string',
	'VideoBSLToggleOff': 								'string',
	'VideoSubsToggleOn': 								'string',
	'VideoSubsToggleOff': 							'string',
	'VideoReturnToMenuUser': 						'string',
	'VideoReturnToMenuAuto': 						'string',
	'VideoSeekUser': 										'string',

	//	Content gallery (images / text) interactive events
	'ContentCategorySelect': 						'string',
	'ContentCategoryExit': 							'string',
	'ContentItemSelectInformed': 				'string',
	'ContentItemSelectUninformed': 			'string',
	'ContentItemExit': 									'string',
	'ContentAnimationStartUser': 				'string',
	'ContentAnimationStartAuto': 				'string',

}





